# Generated by Django 5.1 on 2024-09-03 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("logo", models.URLField()),
                ("flag", models.URLField()),
                ("season", models.IntegerField()),
                ("round", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField()),
                ("winner", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("referee", models.CharField(blank=True, max_length=255, null=True)),
                ("timezone", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("timestamp", models.IntegerField()),
                ("status_long", models.CharField(max_length=255)),
                ("status_short", models.CharField(max_length=10)),
                ("elapsed", models.IntegerField(blank=True, null=True)),
                ("goals_home", models.IntegerField(blank=True, null=True)),
                ("goals_away", models.IntegerField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.league"
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="api.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="api.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Odds",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("values", models.JSONField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds",
                        to="api.match",
                    ),
                ),
            ],
        ),
    ]
