# Generated by Django 5.1 on 2024-10-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
                ('status_long', models.CharField(max_length=255)),
                ('status_short', models.CharField(max_length=10)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('goals_home', models.IntegerField(blank=True, null=True)),
                ('goals_away', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('request_id', models.CharField(max_length=255)),
            ],
        ),
    ]
