# Generated by Django 5.1 on 2024-10-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pastmatch_requestuserrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='wallet',
            field=models.BooleanField(default=True),
        ),
    ]
