name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r coolgoat/requirements.txt

    # - name: Run Tests
    #   env:
    #     DJANGO_DEBUG: True
    #     DJANGO_ALLOWED_HOSTS: localhost,django,127.0.0.1
    #     DJANGO_SECRET_KEY: fo9bsl$h+@mjmktbd6&thas8g2vo2l7ony(-e!v9^^u6yx%tb+
    #     MQTT_HOST: broker.iic2173.org
    #     MQTT_PORT: 9000
    #     MQTT_USERNAME: students
    #     MQTT_PASSWORD: iic2173-2024-2-students
    #     MQTT_TOPIC_INFO: fixtures/info
    #     MQTT_TOPIC_VALIDATIONS: fixtures/validation
    #     MQTT_TOPIC_REQUESTS: fixtures/request
    #     MQTT_TOPIC_HISTORY: fixtures/history
    #   run: |
    #     python coolgoat/manage.py test api.tests.trivial_test

    - name: Configure AWS Credentials je
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2 
      with:
        registry-type: public

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: t4y0j0c2
        REPOSITORY: coolgoat-api
      run: |
        cd coolgoat
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-django .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-django
        cd ..
        cd mqtt_subscriber
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-subscriber .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-subscriber
        cd ..
        cd mqtt_subscriber_history
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-history .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-history
        cd ..
        cd mqtt_subscriber_validations
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-validations .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-validations
        cd ..
        cd mqtt_subscriber_requests_listen
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-requests .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-mqtt-requests